version: 2
jobs:
  test:
    working_directory: ~/circle
    docker:
      - image: ministryofjustice/ruby:2.5.1
        environment:
          RAILS_ENV: test
    steps:
      - checkout
      - run:
          name: Install correct Bundler version
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
      - run:
          name: bundle install
          command: 'bundle install --deployment --jobs=2 --retry 3 --no-cache --without development'
      - run:
          name: test
          command: 'bundle exec rspec'
  build_and_deploy_to_test:
    working_directory: ~/circle/git/fb-service-token-cache
    docker:
      - image: asmega/fb-builder:latest
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "4a:a2:34:ab:96:b7:42:45:86:7c:bd:ce:ee:70:2a:28"
      - run:
          name: checkout fb-service-token-cache-deploy
          command: "GIT_SSH_COMMAND='ssh -v -i ~/.ssh/id_rsa_4aa234ab96b74245867cbdceee702a28 -o \"IdentitiesOnly=yes\"' git clone git@github.com:ministryofjustice/fb-service-token-cache-deploy.git ~/circle/git/fb-service-token-cache-deploy"
      - run:
          name: persist git crypt key to disk
          command: "echo $ENCODED_GIT_CRYPT_KEY | base64 -d > /root/circle/git_crypt.key"
      - run:
          name: unlock git crypt
          command: "cd ~/circle/git/fb-service-token-cache-deploy && git-crypt unlock /root/circle/git_crypt.key"
      - run:
          name: npm install
          command: 'npm install'
      - setup_remote_docker
      - run:
          name: build and push docker images
          command: './scripts/circleci_build.sh test'
      - run:
          name: deploy to test dev
          command: './scripts/circleci_deploy.sh test dev $KUBE_TOKEN_TEST_DEV'
      - run:
          name: deploy to test staging
          command: './scripts/circleci_deploy.sh test staging $KUBE_TOKEN_TEST_STAGING'
      - run:
          name: deploy to test production
          command: './scripts/circleci_deploy.sh test production $KUBE_TOKEN_TEST_PRODUCTION'
  build_and_deploy_to_integration:
    working_directory: ~/circle/git/fb-service-token-cache
    docker:
      - image: asmega/fb-builder:latest
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "4a:a2:34:ab:96:b7:42:45:86:7c:bd:ce:ee:70:2a:28"
      - run:
          name: checkout fb-service-token-cache-deploy
          command: "GIT_SSH_COMMAND='ssh -v -i ~/.ssh/id_rsa_4aa234ab96b74245867cbdceee702a28 -o \"IdentitiesOnly=yes\"' git clone git@github.com:ministryofjustice/fb-service-token-cache-deploy.git ~/circle/git/fb-service-token-cache-deploy"
      - run:
          name: persist git crypt key to disk
          command: "echo $ENCODED_GIT_CRYPT_KEY | base64 -d > /root/circle/git_crypt.key"
      - run:
          name: unlock git crypt
          command: "cd ~/circle/git/fb-service-token-cache-deploy && git-crypt unlock /root/circle/git_crypt.key"
      - run:
          name: npm install
          command: 'npm install'
      - setup_remote_docker
      - run:
          name: build and push docker images
          command: './scripts/circleci_build.sh integration'
      - run:
          name: deploy to integration dev
          command: './scripts/circleci_deploy.sh integration dev $KUBE_TOKEN_INTEGRATION_DEV'
      - run:
          name: deploy to integration staging
          command: './scripts/circleci_deploy.sh integration staging $KUBE_TOKEN_INTEGRATION_STAGING'
      - run:
          name: deploy to integration production
          command: './scripts/circleci_deploy.sh integration production $KUBE_TOKEN_INTEGRATION_PRODUCTION'
  build_and_deploy_to_live:
    working_directory: ~/circle/git/fb-service-token-cache
    docker:
      - image: asmega/fb-builder:latest
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "4a:a2:34:ab:96:b7:42:45:86:7c:bd:ce:ee:70:2a:28"
      - run:
          name: checkout fb-service-token-cache-deploy
          command: "GIT_SSH_COMMAND='ssh -v -i ~/.ssh/id_rsa_4aa234ab96b74245867cbdceee702a28 -o \"IdentitiesOnly=yes\"' git clone git@github.com:ministryofjustice/fb-service-token-cache-deploy.git ~/circle/git/fb-service-token-cache-deploy"
      - run:
          name: persist git crypt key to disk
          command: "echo $ENCODED_GIT_CRYPT_KEY | base64 -d > /root/circle/git_crypt.key"
      - run:
          name: unlock git crypt
          command: "cd ~/circle/git/fb-service-token-cache-deploy && git-crypt unlock /root/circle/git_crypt.key"
      - run:
          name: npm install
          command: 'npm install'
      - setup_remote_docker
      - run:
          name: build and push docker images
          command: './scripts/circleci_build.sh live'
      - run:
          name: deploy to live dev
          command: './scripts/circleci_deploy.sh live dev $KUBE_TOKEN_LIVE_DEV'
      - run:
          name: deploy to live staging
          command: './scripts/circleci_deploy.sh live staging $KUBE_TOKEN_LIVE_STAGING'
      - run:
          name: deploy to live production
          command: './scripts/circleci_deploy.sh live production $KUBE_TOKEN_LIVE_PRODUCTION'

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build_and_deploy_to_test:
          requires:
            - test
          filters:
            branches:
              only: master
      - confirm_integration_deploy:
          type: approval
          requires:
            - build_and_deploy_to_test
      - build_and_deploy_to_integration:
          requires:
            - confirm_integration_deploy
      - confirm_live_deploy:
          type: approval
          requires:
            - build_and_deploy_to_integration
      - build_and_deploy_to_live:
          requires:
            - confirm_live_deploy
